import { SignInButton, useUser } from "@clerk/nextjs";

import Feed from "../components/Feed";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  console.log(user);
  if (!user) return null;
  return (
    <div className="flex w-full gap-5">
      <Image
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-10 w-10 rounded-full"
        width={40}
        height={40}
      />
      <input
        placeholder="Type some emojis!"
        className="w-full bg-transparent"
      />
    </div>
  );
};

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  if (!userLoaded) return <div />;

  // React Query is using cache, so even tho we don't store data here but in component Feed, they will be prepared in cache
  api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-300 md:max-w-2xl">
          <div className="flex border-b border-slate-500 p-4 ">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton>
                  <button className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
                    Sign In
                  </button>
                </SignInButton>
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
